### ISSUE TITLE
uan-config-import failing with OOMKill on NERSC systems for uan 2.5.10 and 2.5.11

### ISSUE THREAD

**Issue by dmjacobsen** [Cray-HPE/uan#73]
Need to change memory request/limits up to 512Mi.

```
2023-04-08 11:04:13,903 - cf-gitea-import - INFO - Attempting to fetch gitea repository: http://gitea-vcs/api/v1/repos/cray/uan-config-management
2023-04-08 11:04:13,999 - cf-gitea-import - INFO - Cloning repository: uan-config-management
Traceback (most recent call last):
  File "/opt/csm/cf-gitea-import/./import.py", line 402, in <module>
    git_repo = clone_repo(
  File "/opt/csm/cf-gitea-import/./import.py", line 119, in clone_repo
    return Repo.clone_from(clone_url, workdir)
  File "/usr/lib/python3.9/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/usr/lib/python3.9/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/lib/python3.9/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/usr/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v http://crayvcs:*****@gitea-vcs/cray/uan-config-management.git /tmp/uan
  stderr: 'Cloning into '/tmp/uan'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (gzip 1517 to 789 bytes)
fatal: fetch-pack: invalid index-pack output
'
```

I suspect the real bug is that it's trying to pull down the gitea repo into a tmpfs.  We have a lot of branches and content in our various repos -- it might be best to clone only the master branch during this clone (e.g., `git clone --depth 1 <url> -b master`) to ensure site-added content doesn't generate this problem.

**Comment by denniswalker** [comment]
Reference: CASMCMS-8531 - Planned for CSM 1.4.1.

**Comment by denniswalker** [comment]
Pulled into CSM 1.4.0 here https://github.com/Cray-HPE/csm/pull/2119
